'''
// User1: 2:30 - 4:30 pm (said something)
// User 2: 4:30 - 4:32 pm (said something)
// User1: 4:32 - 4:35 pm (said something)
{
    _id: 'Auto generated by MongoDB',
    Zoom_call: "Group Name _ 12 Dec 2023",
    Moderator: [“Name1”,”Name2”],
    Duration: “4 hr 35 min”
    
    Attendance: {
        User1: 240 min 30 sec,
        User2: 2 min 30 sec
    },


    Transcript: [
        {
            start time: 2:30 pm
            end time: 4:35 pm
            sender: User1
            message: "said something"
        tag: [“moderator/user”,”question/answer”] 
        },
        {
            start time: 4:30 pm
            end time: 4:32 pm
            sender: User2
            message: "said something"
        tag: [“moderator/user”,”question/answer”]
        },
        {
            start time: 4:32 pm
            end time: 4:35 pm
            sender: User1
            message: "said something"
        tag: [“moderator/user”,”question/answer”]
        }
    ]


    Chat: [
        {
            timestamp: [11:32, 11:34]
            sender: User1
            message: ["said something", "said something"]
        tag: [“moderator/user”,”question/answer”]
        },
        {
            timestamp: 11:32
            sender: User2
            message: "said something"
        tag: [“moderator/user”,”question/answer”]
        }
    ]


}
'''